# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Distribution function for the Wiener diffusion model
#'
#' Calculates the distribution function for the Wiener diffusion
#' model using the implementation of Blurton et al. (2012).
#'
#' @param rt a vector of responses times ( rt > 0 ).
#' @param ch a vector of accuracy/choice values ( ch = {0,1} ).
#' @param alpha a vector of upper boundaries at which the evidence
#'   accumulation terminations.
#' @param theta a vector of proportions determining the starting
#'   point for the evidence accumulation, where the starting point
#'   zeta = alpha*theta ( 0 >= theta >= 1 ).
#' @param xi a vector of drift rates, the rate of evidence accumulation
#'   ( xi > 0 ).
#' @param tau a vector of residual latencies for the non-decision
#'   component ( tau > 0 ).
#' @param sigma a vector of within-trial variabilities, the drift
#'   coefficient ( sigma > 0; default is 1 ).
#' @param eps the margin of error for the infinite sums being calculated
#'   ( default is 1e-29 ).
#' @param joint indicates whether the conditional ( joint = 0 ) or the
#'   joint ( joint = 1) CDF should be returned ( default is 0 ).
#'
#' @section Notes:
#' For unequal vector lengths, values are recycled.
#'
#' @section References:
#'
#' @return A vector of values for the cumulative distribution.
#'
#' @export
pdiff <- function(rt, ch, alpha, theta, xi, tau, sigma = as.numeric( c(1.0)), eps = 1e-29, parYes = 1L) {
    .Call('seqmodels_pdiff', PACKAGE = 'seqmodels', rt, ch, alpha, theta, xi, tau, sigma, eps, parYes)
}

#' @useDynLib seqmodels
#' @importFrom Rcpp sourceCpp
NULL

#' Likelihood for the Ratcliff diffusion model
#'
#' Calculates the likelihood or log-likelihood (joint or conditional)
#' for the Wiener diffusion model using the implementation of Navarro
#' and Fuss (2009).
#'
#' @param rt a vector of responses times ( rt > 0 ).
#' @param ch a vector of accuracy/choice values ( ch = {0,1} ).
#' @param alpha a vector of upper boundaries at which the evidence
#'   accumulation terminations.
#' @param theta a vector of proportions determining the starting
#'   point for the evidence accumulation, where the starting point
#'   zeta = alpha*theta ( 0 >= theta >= 1 ).
#' @param xi a vector of drift rates, the rate of evidence accumulation
#'   ( xi > 0 ).
#' @param tau a vector of residual latencies for the non-decision
#'   component ( tau > 0 ).
#' @param eta a vector of standard deviations for the trial-to-trial
#'   variability in the drift rate (eta > 0). A value results in no
#'   trial-to-trial variability.
#' @param stheta a vector of the ranges for the uniform variability
#'   about the starting point ( 0 <= theta +/- (stheta/2) <= 1). A
#'   value results in no trial-to-trial variability.
#' @param stau a vector of the ranges for the uniform variability
#'   about the residual latency ( 0 <= tau - (stau/2) ). A
#'   value results in no trial-to-trial variability.
#' @param sigma a vector of within-trial variabilities, the drift
#'   coefficient ( sigma > 0 ).
#' @param eps the margin of error for the infinite sums being calculated
#'   ( default is 1e-29 ).
#' @param ln indicates whether the likelihood (ln = 0 ) or the
#'   log-likelihood ( ln = 1 ) should be calculated ( default is 0 ).
#'
#' @section Notes:
#' For unequal vector lengths, values are recycled.
#'
#' @section References:
#' Navarro, D. J., & Fuss, I. G. (2009). Fast and accurate calculations
#'   for first-passage times in Wiener diffusion models. Journal of
#'   Mathematical Psychology, 53(4), 222-230.
#' Ratcliff, R., & Tuerlinckx, F. (2002). Estimating parameters of the
#'   diffusion model: Approaches to dealing with contaminant reaction
#'   times and parameter variability. Psychonomic Bulletin & Review, 9,
#'   438-481.
#'
#' @return A vector of likelihood or log-likelihood values.
#'
#' @export
ddiff <- function(rt, ch, alpha, theta, xi, tau, eta = as.numeric( c(0.0)), stheta = as.numeric( c(0.0)), stau = as.numeric( c(0.0)), sigma = as.numeric( c(1.0)), eps = 1e-29, ln = 0L, parYes = 1L) {
    .Call('seqmodels_ddiff', PACKAGE = 'seqmodels', rt, ch, alpha, theta, xi, tau, eta, stheta, stau, sigma, eps, ln, parYes)
}

#' Random Deviates from the Wald Distribution
#'
#' Generates random draws from a Wald distribution (i.e. an
#' inverse gaussian), parameterized based on Brownian
#' motion.
#'
#' @param N the number of draws
#' @param kappa a vector of thresholds determining when a decision
#'   terminates (kappa > 0).
#' @param xi a vector of drift rates, or rates of evidence accumulation
#'   (xi > 0).
#' @param sigma a vector of the within-trial variabilities
#'   (sigma > 0).
#'
#' @section Notes:
#' For unequal vector lengths, values are recycled.
#'
#' @section References:
#' Michael, J. R., Schucany, W. R., & Haas, R. W. (1976). Generating
#'   random variates using transformations with multiple roots.
#'   The American Statistician, 30 (2), 88-90. doi:10.2307/2683801.
#'
#' @return Returns a numeric vector consisting of random draws from
#'   the Wald distribution.
#'
#' @examples
#' rinvgauss(8,c(1,2,-1,1),c(1,.5,1,-1),c(1,1,1,1))
#' @export
rinvgauss <- function(N, kappa, xi, sigma) {
    .Call('seqmodels_rinvgauss', PACKAGE = 'seqmodels', N, kappa, xi, sigma)
}

#' Density Function for the Wald Distribution
#'
#' Calculates the density function for the Wald distribution (i.e.
#' an inverse gaussian), parameterized based on Brownian
#' motion.
#'
#' @param kappa a vector of thresholds determining when a decision
#'   terminates (kappa > 0).
#' @param xi a vector of drift rates, or rates of evidence accumulation
#'   (xi > 0).
#' @param sigma a vector of the within-trial variabilities
#'   (sigma > 0).
#' @param ln indicates whether the log-likelihood should be returned,
#'   where 1 = True, 0 = False (the default).
#'
#' @section Notes:
#' For unequal vector lengths, values are recycled.
#'
#' @return Returns a numeric vector consisting of the density (or
#'   log density) for the model.
#'
#' @export
dinvgauss <- function(t, kappa, xi, sigma, ln = 0L) {
    .Call('seqmodels_dinvgauss', PACKAGE = 'seqmodels', t, kappa, xi, sigma, ln)
}

#' Distribution Function for the Wald Distribution
#'
#' Calculates the distribution function for the Wald distribution (i.e.
#' an inverse gaussian), parameterized based on Brownian
#' motion.
#'
#' @param kappa a vector of thresholds determining when a decision
#'   terminates (kappa > 0).
#' @param xi a vector of drift rates, or rates of evidence accumulation
#'   (xi > 0).
#' @param sigma a vector of the within-trial variabilities
#'   (sigma > 0).
#'
#' @section Notes:
#' For unequal vector lengths, values are recycled.
#'
#' @return Returns a numeric vector giving P(T <= t | kappa, xi, sigma).
#'
#' @export
pinvgauss <- function(t, kappa, xi, sigma) {
    .Call('seqmodels_pinvgauss', PACKAGE = 'seqmodels', t, kappa, xi, sigma)
}

#' Random Deviates from the Wald Race Model
#'
#' Simulates a set of response times and choices from a two accumulator
#' version of the Wald race model (Logan et al., 2014).
#'
#' @param N the number of observations to simulate.
#' @param k1 the threshold determining when a decision terminates for
#'   choices == 1 ( k1 > 0).
#' @param xi1 the average rate of evidence accumulation within a trial
#'   for choices == 1 (xi1 > 0).
#' @param tau1 the residual latency for choices == 1 (tau1 >= 0).
#' @param k0 the threshold determining when a decision terminates for
#'   choices == 0 ( k0 > 0).
#' @param xi0 the average rate of evidence accumulation within a trial
#'   for choices == 0 (xi0 > 0).
#' @param tau0 the residual latency for choices == 0 (tau0 >= 0).
#' @param s0 the within trial variability for choices == 0 (s0 > 0).
#' @param s1 the within trial variability for choices == 1 (s1 > 0).
#'
#' @section Notes:
#' For unequal vector lengths, values are recycled. Inadmissible values
#' return NA.
#'
#' @return Returns a matrix with two columns, the first consiting of
#' response times, the second indicate the choice (i.e. the winning
#' accumulator, either 1 or 0).
#'
#' @export
rwaldrace <- function(N, k1, xi1, tau1, k0, xi0, tau0, s1 = as.numeric( c(1.0)), s0 = as.numeric( c(1.0))) {
    .Call('seqmodels_rwaldrace', PACKAGE = 'seqmodels', N, k1, xi1, tau1, k0, xi0, tau0, s1, s0)
}

#' Density Function for the Wald Race Model
#'
#' Calculates the joint density for a two choice version of the Wald race
#' model.
#'
#' @param rt a vector of response times (rt > 0).
#' @param ch a vector of choices (ch = {0,1}).
#' @param k1 the threshold determining when a decision terminates for
#'   choices == 1 ( k1 > 0).
#' @param xi1 the average rate of evidence accumulation within a trial
#'   for choices == 1 (xi1 > 0).
#' @param tau1 the residual latency for choices == 1 (tau1 >= 0).
#' @param k0 the threshold determining when a decision terminates for
#'   choices == 0 ( k0 > 0).
#' @param xi0 the average rate of evidence accumulation within a trial
#'   for choices == 0 (xi0 > 0).
#' @param tau0 the residual latency for choices == 0 (tau0 >= 0).
#' @param s0 the within trial variability for choices == 0 (s0 > 0;
#'   default is 1.0).
#' @param s1 the within trial variability for choices == 1 (s1 > 0;
#'   default is 1.0).
#' @param ln indicates whether the log-likelihood should be returned,
#'   where 1 = True, 0 = False (the default).
#'
#' @section Notes:
#' For unequal vector lengths, values are recycled.
#'
#' @return Returns the joint likelihood (or the log-likelihood) for the
#' two-choice version of the Wald race model.
#'
#' @export
dwaldrace <- function(rt, ch, k1, xi1, tau1, k0, xi0, tau0, s1 = as.numeric( c(1.0)), s0 = as.numeric( c(1.0)), ln = 0L) {
    .Call('seqmodels_dwaldrace', PACKAGE = 'seqmodels', rt, ch, k1, xi1, tau1, k0, xi0, tau0, s1, s0, ln)
}

